#!/bin/bash

patch dependence/InAppSettingsKit/InAppSettingsKit/Controllers/IASKAppSettingsViewController.m dependence/patchs/InAppSettingsKit/IASKAppSettingsViewController.m.diff
patch dependence/InAppSettingsKit/InAppSettingsKit/Models/IASKSettingsReader.h dependence/patchs/InAppSettingsKit/IASKSettingsReader.h.diff
patch dependence/InAppSettingsKit/InAppSettingsKit/Xibs/IASKPSTextFieldSpecifierViewCell.xib dependence/patchs/InAppSettingsKit/IASKPSTextFieldSpecifierViewCell.xib.diff
patch dependence/InAppSettingsKit/InAppSettingsKit/Xibs/IASKPSToggleSwitchSpecifierViewCell.xib dependence/patchs/InAppSettingsKit/IASKPSToggleSwitchSpecifierViewCell.xib.diff
